In [14]:
import pandas as pd

In [15]:
# reading the CSV file from the web site
df_premier21 = pd.read_csv('https://www.football-data.co.uk/mmz4281/2122/E0.csv')

In [17]:
# showing the data frame
df_premier21

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [20]:
# rename the columns
df_premier21.rename(columns={
    'FTHG': 'Home Goals',
    'FTAG': 'Away Goals',
    }, inplace=True)

# showing the updated data frame
df_premier21.head()

,Div,Date,Time,HomeTeam,AwayTeam,Home Goals,Away Goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86

# Read .CSV file from multiple Url

##### link: root + season + league

In [22]:
# link structure
"https://www.football-data.co.uk/mmz4281/" + "2122" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2122/E0.csv'

In [23]:
# Create root variable
root = "https://www.football-data.co.uk/mmz4281/"

##### Multiple leagues

- https://www.football-data.co.uk/mmz4281/2122/E0.csv
- https://www.football-data.co.uk/mmz4281/2122/E1.csv
- https://www.football-data.co.uk/mmz4281/2122/E2.csv
- https://www.football-data.co.uk/mmz4281/2122/E3.csv
- https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [30]:
# Create list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']

# Loop through leagues, read multiple CSV and append to a list
frames = []

for league in leagues:
    df = pd.read_csv(f"{root}2122/{league}.csv", encoding = 'ISO-8859-1')	
    frames.append(df)

In [31]:
# Length of the frames
len(frames)

5

In [34]:
# Show 1st, 2nd, and 3rd elements
frames[0].head()
frames[1].head()
frames[2].head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E2,07/08/2021,15:00,Bolton,Milton Keynes Dons,3,3,D,1,1,...,1.97,-0.25,1.90,1.95,1.91,1.97,1.99,2.01,1.90,1.92
1,E2,07/08/2021,15:00,Cambridge,Oxford,1,1,D,0,1,...,1.86,0.25,2.08,1.73,2.12,1.78,2.12,1.82,2.06,1.77
2,E2,07/08/2021,15:00,Crewe,Cheltenham,1,1,D,1,1,...,1.69,-0.25,2.00,1.85,1.99,1.90,2.04,1.95,1.96,1.87
3,E2,07/08/2021,15:00,Doncaster,AFC Wimbledon,1,2,A,0,0,...,1.88,-0.25,2.10,1.77,2.11,1.80,2.12,1.82,2.07,1.77
4,E2,07/08/2021,15:00,Fleetwood Town,Portsmouth,0,1,A,0,0,...,1.60,0.00,2.05,1.80,2.09,1.82,2.13,1.86,2.07,1.78